### ISSUE TITLE
The executable  run001/bin/findLats.sh does not exist

### ISSUE THREAD

**Issue by xxjjyy69** [RDCEP/psims#12]
Hi all, 
When I run a single tile via swift, an error occurs.

Directory: psims-all-20170613-1355-a68091t6/jobs/2/findLats-28sgqi9n
Caused by:
	The executable /home/joyxu/psims-release-2.0/run018/bin/findLats.sh does not exist
Caused by:
	Job failed with and exit code of 254
org.globus.cog.abstraction.impl.common.execution.JobException: Job failed with and exit code of 254 (exit code: -2)
	atorg.globus.cog.abstraction.coaster.service.local.JobStatusHandler.requestComplete(JobStatusHandler.java:40)
	at org.globus.cog.coaster.handlers.RequestHandler.receiveCompleted(RequestHandler.java:88)
	atorg.globus.cog.coaster.channels.AbstractCoasterChannel.handleRequest(AbstractCoasterChannel.java:536)
	atorg.globus.cog.coaster.channels.AbstractStreamCoasterChannel.stepNIO(AbstractStreamCoasterChannel.java:238)
	at org.globus.cog.coaster.channels.NIOMultiplexer.loop(NIOMultiplexer.java:97)
	at org.globus.cog.coaster.channels.NIOMultiplexer.run(NIOMultiplexer.java:56)

Caused by:
	Job failed with and exit code of 254
org.globus.cog.abstraction.impl.common.execution.JobException: Job failed with and exit code of 254 (exit code: -2)
	atorg.globus.cog.abstraction.coaster.service.local.JobStatusHandler.requestComplete(JobStatusHandler.java:40)
	at org.globus.cog.coaster.handlers.RequestHandler.receiveCompleted(RequestHandler.java:88)
	atorg.globus.cog.coaster.channels.AbstractCoasterChannel.handleRequest(AbstractCoasterChannel.java:536)
	atorg.globus.cog.coaster.channels.AbstractStreamCoasterChannel.stepNIO(AbstractStreamCoasterChannel.java:238)
	at org.globus.cog.coaster.channels.NIOMultiplexer.loop(NIOMultiplexer.java:97)
	at org.globus.cog.coaster.channels.NIOMultiplexer.run(NIOMultiplexer.java:56)
 (exit code: -16843010)

Execution failed:
Execution completed with errors
	throw @ swift.k, line: 112

I'd appreciate if someone cloud help me

**Comment by xxjjyy69** [comment]
Actually, I have solved the problem by myself. Just modify executable file path in conf/swift.properties.
