### ISSUE TITLE
Error using pip requirements installation

### ISSUE THREAD

**Issue by rtrepos** [RDCEP/psims#19]
Hello,
I am trying to install pDSSAT and I have an error that occurs at the very beginning when I try to install requirements :  'pip install -r requirements.txt'
I am using Ubintu 16.04.
Any help is welcome. Below you will find the traceback of the call.
Best regards
Ronan

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-RjdBTr/Rtree/setup.py", line 4, in <module>
        import rtree
      File "rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "rtree/index.py", line 6, in <module>
        from . import core
      File "rtree/core.py", line 110, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
        func = self.__getitem__(name)
      File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: /usr/bin/python: undefined symbol: Error_GetLastErrorNum

**Comment by DavidMichaelKelly** [comment]
Hello there. If rtree is giving you issues, you can safely remove it from requirements.txt. It's only used in one of the adjacent utilities we use, not in psims itself.

**Comment by rtrepos** [comment]
Hi David and thank you for the answer, it worked !
Now, I am trying to compile dssat-csm using the Makefile.
But the Intel fortran compiler (ifort) is required and I don't have it. Is it possible to use the gfortan compiler instead ? I have already succeeded to install DSSAT 4.7.2 using gfortran (outside the pSIMS framework)

When I try to use gfortran instead of ifort in the pSIMS ramework, I have to remove the '--fixed' option and I have an error (see below). Any idea ?
Thanks
Ronan

--
gfortran -c ModuleDefs.for
ModuleDefs.for:433:1:

 D       STDPATH = 'D:\DSSAT46\' 
 1
Error: Non-numeric character in statement label at (1)
ModuleDefs.for:521:9:

       USE ModuleDefs
         1
Fatal Error: Can't open module file ‘moduledefs.mod’ for reading at (1): Aucun fichier ou dossier de ce type
compilation terminated.

**Comment by DavidMichaelKelly** [comment]
I know some people have successfully used gfortran to compile dssat, but I've never been able to get that to work so I'm not sure what's involved. You could try reaching out to the dssat group and see if they have any advice on how to do that. Another option would be to download and install a trial version of ifort, compile dssat, then uninstall ifort when the trial expires.
